### PR TITLE
Show reminders

### LINKED ISSUE #3: Show reminders in dosage list
It would be helpful to see both that a reminder exists, and how long is remining for each dosage that has a reminder. If the reminder time has passed, no need to show the indication. 

[Enchant request](https://pilllogger.enchant.com/spa/ticket/56638dcf69702d0da8000009)

>Is it possible to see how much time remains on the timers? That would save having to revisit the bottles. I guess I could add it in the note.

### PR DESCRIPTION
**Pull request by lxalln**
This change means we now store the reminder time in the db when a reminder is chosen.
If the reminder is after now, we show the remaining time in the consumption list.

Fixes #3

### CODE REVIEW

**Comment by lxalln** [comment]
@Dreagen could you look through this and let me know if it's ok for release?

**Comment by Dreagen** [comment]
This appears to be working fine. Do i need to do something to this?

**Comment by lxalln** [comment]
You wanted me to change it to show on the Pill.
Up to you, we could release without that and add it later. What do you reckon?

**Comment by Dreagen** [comment]
hmmm, I'll let you decide. Jem and I think it makes sense on the pill as well but I can see the logic for not having it there. I don't think it's a big bother either way

**Comment by lxalln** [comment]
I agree it makes sense, and I think we should do it. But it's a question of whether we wait until one of us implements it, or whether we release "half done"

**Comment by Dreagen** [comment]
Well I think we can release now and add it later. It works as it is no reason to hold onto it imo

**Comment by lxalln** [comment]
Cool cool, GitHub says we can merge it, so whenever you're ready.

Obviously I haven't done the release notes or anything like that.

**Pull request merged**
